#!/usr/bin/env python3
"""
Laizer Patch v9 — Centre/Worker ID integrity, Notices delivery bug,
Report cache invalidation.

Run from the project root (the folder that contains `mobile/` and
`backend/`):

    python3 patch_laizer_v9.py            # apply
    python3 patch_laizer_v9.py --dry-run  # preview only, writes nothing
    python3 patch_laizer_v9.py --undo     # restore the .bak9 files

WHAT WAS BROKEN & WHAT THIS CHANGES
────────────────────────────────────────────────────────────────────────
1. Centre IDs (STN-XX) did not renumber after a delete, and — more
   importantly — `Centre.centreId` was UNIQUE ACROSS THE WHOLE DATABASE,
   not per owner. That means owner B could never get "STN-01" if owner A
   already had it, and it left no clean way to tell two owners' branches
   apart by Centre ID alone (which is exactly what worker login relied on).
   FIX:
     • prisma/schema.prisma — `centreId`/`centreNo` uniqueness moved from
       a bare column constraint to a compound `[ownerId, centreId]` /
       `[ownerId, centreNo]` index. Every owner's first centre is now
       always STN-01, independent of every other owner.
     • backend/src/routes/centres.js — DELETE now calls a new
       `renumberCentres()` helper that closes the gap immediately, so
       STN-01..STN-NN always stays contiguous for that owner. POST's
       ID-generation loop is scoped to the owner instead of scanning the
       whole table.
     • User gets a new `workerCode` column (e.g. "WK-A1B2"), generated by
       the owner-side worker-registration endpoint. Worker login now
       accepts an optional `workerId` alongside `centreId`. When a Worker
       ID is supplied, login is resolved worker → their own active
       assignment → that assignment's centre, so identical Centre-ID
       strings from different owners can never be confused with each
       other. Centre-ID-only ("guest branch") login still works, but only
       when the Centre ID is unambiguous AND that centre has no worker
       registered yet — otherwise the person is asked for their Worker ID.
     • mobile: login screen gets a "Worker ID" field; the worker
       registration screen shows/returns the generated code so the owner
       can hand it to the worker.

2. Notices silently failed end-to-end. `backend/src/routes/notices.js`
   reads/writes an `expiresAt` field on the `Notice` model that was never
   defined in `prisma/schema.prisma` — every create/list call threw a
   Prisma "unknown argument" error under the hood. The owner's GET has a
   catch-all that swallows this into an empty list, and the worker's GET
   isn't wrapped at all, so notices never reliably showed up on either
   side. FIX: `expiresAt DateTime?` added to the `Notice` model so the
   field the route code already expects actually exists.

3. Daily/weekly report cards didn't reflect new services. The report
   endpoints cache under `report:d:<centreId-or-ownerId>:<date>` — the
   owner's "all centres" dashboard view caches under the OWNER's id (see
   `centreId || ownerId` in reports.js), but `services.js` only ever
   invalidated the CENTRE-id cache key when a service event was logged.
   The aggregate dashboard card kept serving a stale cached value until
   the TTL (10–30 min) expired on its own. FIX: a single
   `bustReportCaches()` helper now wildcard-invalidates every report
   cache variant (daily, weekly, and the per-centre detail card) for the
   affected date in one call, regardless of which id it was cached under.
   The previously-uncached `/api/reports/detail/` endpoint (used by the
   report "cards") is now cached too, with the same invalidation path —
   faster app loading without the staleness bug.

This script is idempotent: re-running it after it already applied is a
no-op (it detects already-applied changes per file and skips them).

AFTER RUNNING THIS SCRIPT
────────────────────────────────────────────────────────────────────────
  cd backend
  npx prisma generate
  npx prisma db push        # pushes the schema changes to Supabase
  # restart the backend (Render redeploy / local `npm run dev`)

Existing centres keep their current STN-XX id until the next delete on
that owner's account triggers a renumber. Existing workers have no
Worker ID until you re-save/re-register them (or run a one-off backfill
— ask if you'd like a script for that).
"""
import sys, os, shutil

DRY  = '--dry-run' in sys.argv
UNDO = '--undo'    in sys.argv

G='\033[92m'; Y='\033[93m'; B='\033[94m'; R='\033[91m'; E='\033[0m'
def ok(m):   print(f'{G}[ OK ]{E}  {m}')
def warn(m): print(f'{Y}[WARN]{E}  {m}')
def info(m): print(f'{B}[INFO]{E}  {m}')
def err(m):  print(f'{R}[ERR ]{E}  {m}')

ROOT = os.path.dirname(os.path.abspath(__file__))

def fp(rel):
    return os.path.join(ROOT, rel)

def find_root():
    """Allow running the script from one level above the repo too."""
    global ROOT
    if os.path.isdir(fp('mobile')) and os.path.isdir(fp('backend')):
        return
    for child in os.listdir(ROOT):
        cand = os.path.join(ROOT, child)
        if os.path.isdir(os.path.join(cand, 'mobile')) and os.path.isdir(os.path.join(cand, 'backend')):
            ROOT = cand
            return

find_root()

BAK_EXT = '.bak9'
MARKER  = '__LAIZER_PATCH_V9__'

def read(rel):
    p = fp(rel)
    if not os.path.exists(p):
        return None
    with open(p, 'r', encoding='utf-8') as f:
        return f.read()

def write(rel, content):
    p = fp(rel)
    if DRY:
        info(f'(dry-run) would write {rel}')
        return
    os.makedirs(os.path.dirname(p), exist_ok=True)
    if os.path.exists(p) and not os.path.exists(p + BAK_EXT):
        shutil.copy2(p, p + BAK_EXT)
    with open(p, 'w', encoding='utf-8') as f:
        f.write(content)
    ok(f'wrote {rel}')

def undo_all():
    count = 0
    for dirpath, _dirs, files in os.walk(ROOT):
        if 'node_modules' in dirpath or '.git' in dirpath:
            continue
        for fn in files:
            if fn.endswith(BAK_EXT):
                bak  = os.path.join(dirpath, fn)
                orig = bak[: -len(BAK_EXT)]
                shutil.move(bak, orig)
                ok(f'restored {os.path.relpath(orig, ROOT)}')
                count += 1
    if count == 0:
        warn('No .bak9 files found — nothing to undo.')
    else:
        ok(f'Restored {count} file(s).')
    sys.exit(0)

if UNDO:
    undo_all()

if not (os.path.isdir(fp('mobile')) and os.path.isdir(fp('backend'))):
    err('Could not find mobile/ and backend/ next to this script. '
        'Place patch_laizer_v9.py at the project root and re-run.')
    sys.exit(1)

info(f'Project root: {ROOT}')
if DRY:
    info('Dry run — no files will be modified.')

CHANGED_FILES = []

def patch_file(rel, replacements, label):
    """
    Apply a list of (old, new) exact-string replacements to a file.
    Skips (idempotently) any replacement whose `new` text is already
    present. Warns (but still proceeds) if `old` is not found at all —
    that means the file has drifted from what this patch expects.
    """
    content = read(rel)
    if content is None:
        err(f'{label}: file not found — {rel}')
        return False

    changed = False
    for old, new, desc in replacements:
        if new in content:
            info(f'{label}: "{desc}" already applied — skipping')
            continue
        if old not in content:
            warn(f'{label}: could not locate anchor for "{desc}" — '
                 f'file may already differ from what this patch expects. Skipping this hunk.')
            continue
        count = content.count(old)
        if count > 1:
            warn(f'{label}: anchor for "{desc}" is not unique ({count} matches) — '
                 f'replacing first occurrence only.')
        content = content.replace(old, new, 1)
        changed = True
        ok(f'{label}: applied "{desc}"')

    if changed:
        write(rel, content)
        CHANGED_FILES.append(rel)
    else:
        info(f'{label}: nothing to do')
    return changed

def rewrite_file(rel, new_content, label):
    """Full-file rewrite, skipped idempotently if the marker is already present."""
    content = read(rel)
    if content is not None and MARKER in content:
        info(f'{label}: already patched — skipping')
        return False
    write(rel, new_content)
    CHANGED_FILES.append(rel)
    ok(f'{label}: rewritten')
    return True


# ════════════════════════════════════════════════════════════════════════
# 1. backend/prisma/schema.prisma
# ════════════════════════════════════════════════════════════════════════
patch_file('backend/prisma/schema.prisma', [
    (
        '  nim             String?                  @unique\n'
        '  passwordHash    String?                  @map("password_hash")\n',

        '  nim             String?                  @unique\n'
        '  workerCode      String?                  @unique @map("worker_code") // ' + MARKER + '\n'
        '  passwordHash    String?                  @map("password_hash")\n',

        'add User.workerCode (worker login credential, generated at registration)',
    ),
    (
        '  centreNo      String                   @unique @map("centre_no")\n'
        '  centreId      String                   @unique @map("centre_id")\n',

        '  centreNo      String                   @map("centre_no") // ' + MARKER + ' — uniqueness now scoped per-owner below\n'
        '  centreId      String                   @map("centre_id")\n',

        'de-globalize Centre.centreId / centreNo uniqueness',
    ),
    (
        '  @@index([ownerId])\n'
        '  @@map("centres")\n'
        '}',

        '  @@index([ownerId])\n'
        '  @@unique([ownerId, centreId], name: "centre_owner_centreId")\n'
        '  @@unique([ownerId, centreNo], name: "centre_owner_centreNo")\n'
        '  @@map("centres")\n'
        '}',

        'scope Centre ID uniqueness to [ownerId, centreId] so every owner can have STN-01',
    ),
    (
        '  priority  NoticePriority @default(normal)\n'
        '  createdAt DateTime       @default(now()) @map("created_at")\n'
        '  reads     NoticeRead[]\n',

        '  priority  NoticePriority @default(normal)\n'
        '  createdAt DateTime       @default(now()) @map("created_at")\n'
        '  expiresAt DateTime?      @map("expires_at") // ' + MARKER + ' — routes/notices.js already relies on this field\n'
        '  reads     NoticeRead[]\n',

        'add missing Notice.expiresAt column (root cause of notices not saving/loading)',
    ),
], 'schema.prisma')


# ════════════════════════════════════════════════════════════════════════
# 2. backend/src/routes/centres.js — full rewrite (owner-scoped IDs +
#    auto-renumber on delete)
# ════════════════════════════════════════════════════════════════════════
CENTRES_JS = '''/**
 * SMSS — Centres routes (owner only)
 *
 * GET    /api/centres/           — list owner's active centres
 * POST   /api/centres/           — create centre
 * GET    /api/centres/:id/       — centre detail + active workers
 * PATCH  /api/centres/:id/       — update name/location
 * DELETE /api/centres/:id/       — hard delete + auto-renumber remaining centres
 *
 * ''' + MARKER + '''
 * Centre IDs (STN-XX) are scoped PER OWNER (see prisma schema — the unique
 * constraint moved from a bare `centreId` column to a compound
 * [ownerId, centreId] index), so every owner's first centre is always
 * STN-01 regardless of what other owners have created. Deleting a centre
 * now closes the gap immediately — remaining centres are renumbered so the
 * sequence STN-01..STN-NN always stays contiguous, matching what the owner
 * sees on screen.
 */
const { Router }       = require('express');
const { z }            = require('zod');
const prisma           = require('../lib/prisma');
const redis            = require('../lib/redis');
const logAction        = require('../lib/audit');
const { authenticate, ownerOnly } = require('../middleware/auth');

const router = Router();
router.use(authenticate, ownerOnly);

// Renumber all of an owner's active centres to a contiguous STN-01..STN-NN
// sequence, ordered by original creation time. Safe to call any time (it's
// a no-op if the sequence is already contiguous) — called after every
// delete so gaps never appear.
async function renumberCentres(ownerId) {
  const centres = await prisma.centre.findMany({
    where:   { ownerId, isActive: true },
    orderBy: { createdAt: 'asc' },
  });

  const updates = [];
  centres.forEach((c, idx) => {
    const target = `STN-${String(idx + 1).padStart(2, '0')}`;
    if (c.centreId !== target || c.centreNo !== target) {
      updates.push(prisma.centre.update({
        where: { id: c.id },
        data:  { centreId: target, centreNo: target },
      }));
    }
  });

  if (updates.length) await prisma.$transaction(updates);
  return centres.length;
}

// ── GET /api/centres/ ─────────────────────────────────────────────────────────
router.get('/', async (req, res, next) => {
  try {
    const ownerId  = req.user.id;
    const cacheKey = redis.CacheKey.centres(ownerId);
    let centres    = await redis.cacheGet(cacheKey);

    if (!centres) {
      centres = await prisma.centre.findMany({
        where:   { ownerId, isActive: true },
        orderBy: { createdAt: 'asc' },
        include: {
          _count: { select: { assignments: { where: { isActive: true } } } },
        },
      });
      await redis.cacheSet(cacheKey, centres, redis.CacheTTL.CENTRES);
    }
    return res.json(centres);
  } catch (err) { next(err); }
});

// ── POST /api/centres/ ────────────────────────────────────────────────────────
const CreateCentreSchema = z.object({
  name:     z.string().min(2).transform(s => s.trim().toUpperCase()),
  location: z.string().min(2).transform(s => s.trim().toUpperCase()),
});

router.post('/', async (req, res, next) => {
  try {
    const parsed = CreateCentreSchema.safeParse(req.body);
    if (!parsed.success)
      return res.status(400).json({ error: 'validation_error', detail: parsed.error.flatten() });

    const { name, location } = parsed.data;

    // Auto-generate STN-XX — scoped to THIS owner only (a compound
    // [ownerId, centreId] unique index in the schema allows different
    // owners to both have a "STN-01"). Gap-safe: since renumberCentres()
    // keeps the sequence contiguous after every delete, this is normally
    // just "count of active centres + 1", but we still scan for a free
    // slot defensively in case of concurrent requests.
    const count = await prisma.centre.count({ where: { ownerId: req.user.id, isActive: true } });
    let seq = count + 1;
    let centreId;
    for (let i = 0; i < 100; i++) {
      const candidate = `STN-${String(seq).padStart(2, '0')}`;
      const exists    = await prisma.centre.findFirst({ where: { ownerId: req.user.id, centreId: candidate } });
      if (!exists) { centreId = candidate; break; }
      seq++;
    }
    if (!centreId)
      return res.status(500).json({ error: 'id_exhausted', detail: 'Could not generate a unique Centre ID.' });

    const centreNo = centreId;
    console.log(`[Centres] Creating: ${JSON.stringify({ centreId, name, location, owner: req.user.id })}`);

    let centre;
    try {
      centre = await prisma.centre.create({
        data: { centreNo, centreId, name, location, ownerId: req.user.id },
      });
      console.log(`[Centres] Created OK: ${centre.id} (${centreId})`);
    } catch (dbErr) {
      console.error('[Centres] DB error:', dbErr?.message ?? dbErr);
      return res.status(500).json({
        error: 'db_error',
        detail: `Database error: ${dbErr?.message ?? 'Unknown DB error'}`,
      });
    }

    await redis.cacheDel(redis.CacheKey.centres(req.user.id));
    await logAction(req.user.id, logAction.ACTIONS.CENTRE_CREATED, { req, centreId: centre.id });
    return res.status(201).json(centre);
  } catch (err) { next(err); }
});

// ── GET /api/centres/:id/ ─────────────────────────────────────────────────────
router.get('/:id/', async (req, res, next) => {
  try {
    const centre = await prisma.centre.findFirst({
      where:   { id: req.params.id, ownerId: req.user.id },
      include: {
        assignments: {
          where:   { isActive: true },
          include: { worker: { select: { id:true, fullName:true, nim:true, phone:true, workerCode:true } } },
        },
      },
    });
    if (!centre) return res.status(404).json({ error: 'not_found', detail: 'Centre not found.' });
    return res.json(centre);
  } catch (err) { next(err); }
});

// ── PATCH /api/centres/:id/ ───────────────────────────────────────────────────
router.patch('/:id/', async (req, res, next) => {
  try {
    const { name, location } = req.body;
    const centre = await prisma.centre.updateMany({
      where: { id: req.params.id, ownerId: req.user.id },
      data:  { ...(name ? { name } : {}), ...(location ? { location } : {}) },
    });
    if (!centre.count) return res.status(404).json({ error: 'not_found', detail: 'Centre not found.' });
    await redis.cacheDel(redis.CacheKey.centres(req.user.id));
    return res.json({ detail: 'Centre updated.' });
  } catch (err) { next(err); }
});

// ── DELETE /api/centres/:id/ — hard-delete, then close the ID gap ────────────
router.delete('/:id/', authenticate, ownerOnly, async (req, res, next) => {
  try {
    const centre = await prisma.centre.findFirst({
      where: { id: req.params.id, ownerId: req.user.id },
    });
    if (!centre) return res.status(404).json({ error: 'not_found', detail: 'Centre not found.' });

    await prisma.workerCentreAssignment.deleteMany({ where: { centreId: centre.id } });
    await prisma.stockItem.deleteMany({ where: { centreId: centre.id } });
    await prisma.serviceEvent.deleteMany({ where: { centreId: centre.id } });
    await prisma.notice.deleteMany({ where: { centreId: centre.id } });
    await prisma.centre.delete({ where: { id: centre.id } });

    // Close the gap: STN-01, STN-02… stays contiguous for this owner.
    await renumberCentres(req.user.id);

    await redis.cacheDel(redis.CacheKey.centres(req.user.id));
    await logAction(req.user.id, 'CENTRE_DELETED', { req, centreId: centre.id });
    return res.json({ detail: 'Centre deleted successfully. Remaining centres were renumbered.' });
  } catch (err) { next(err); }
});

module.exports = router;
'''
rewrite_file('backend/src/routes/centres.js', CENTRES_JS, 'centres.js')


# ════════════════════════════════════════════════════════════════════════
# 3. backend/src/routes/workers.js — generate + expose workerCode
# ════════════════════════════════════════════════════════════════════════
patch_file('backend/src/routes/workers.js', [
    (
        "// Verify a centre belongs to this owner\n"
        "async function ownCentre(centreId, ownerId) {\n"
        "  return prisma.centre.findFirst({ where: { id: centreId, ownerId, isActive: true } });\n"
        "}\n",

        "// Verify a centre belongs to this owner\n"
        "async function ownCentre(centreId, ownerId) {\n"
        "  return prisma.centre.findFirst({ where: { id: centreId, ownerId, isActive: true } });\n"
        "}\n"
        "\n"
        "// " + MARKER + "\n"
        "// Generate a globally-unique, worker-facing login code. Independent of\n"
        "// Centre ID numbering (which is now scoped per-owner) — this is what lets\n"
        "// the login endpoint tell workers of different owners apart even when\n"
        "// their Centre IDs collide (e.g. two owners both having a \"STN-01\").\n"
        "async function generateWorkerCode() {\n"
        "  for (let i = 0; i < 50; i++) {\n"
        "    const rand = Math.random().toString(36).slice(2, 6).toUpperCase();\n"
        "    const candidate = `WK-${rand}`;\n"
        "    const exists = await prisma.user.findUnique({ where: { workerCode: candidate } });\n"
        "    if (!exists) return candidate;\n"
        "  }\n"
        "  // Extremely unlikely fallback — still unique-checked by the DB constraint.\n"
        "  return `WK-${Date.now().toString(36).toUpperCase().slice(-6)}`;\n"
        "}\n",

        'add generateWorkerCode() helper',
    ),
    (
        "    const worker = await prisma.user.create({\n"
        "      data: { fullName, phone, role: 'worker' },\n"
        "    });\n",

        "    const worker = await prisma.user.create({\n"
        "      data: { fullName, phone, role: 'worker', workerCode: await generateWorkerCode() },\n"
        "    });\n",

        'assign workerCode on worker creation',
    ),
    (
        "    await redis.cacheDel(redis.CacheKey.workers(req.user.id));\n"
        "    await logAction(req.user.id, logAction.ACTIONS.WORKER_REGISTERED, { req, workerId: worker.id });\n"
        "    return res.status(201).json({ id: worker.id, fullName: worker.fullName, phone: worker.phone });\n",

        "    await redis.cacheDel(redis.CacheKey.workers(req.user.id));\n"
        "    await logAction(req.user.id, logAction.ACTIONS.WORKER_REGISTERED, { req, workerId: worker.id });\n"
        "    return res.status(201).json({\n"
        "      id: worker.id, fullName: worker.fullName, phone: worker.phone,\n"
        "      workerCode: worker.workerCode, // give this to the worker for login\n"
        "    });\n",

        'return workerCode in the registration response',
    ),
    (
        "    return res.json(workers.map(w => ({\n"
        "      id:           w.id,\n"
        "      fullName:     w.fullName,\n"
        "      nim:          w.nim,\n"
        "      phone:        w.phone,\n"
        "      isActive:     w.isActive,\n"
        "      assignedCentre: w.assignments?.[0]?.centre || null,\n"
        "    })));\n",

        "    return res.json(workers.map(w => ({\n"
        "      id:           w.id,\n"
        "      fullName:     w.fullName,\n"
        "      nim:          w.nim,\n"
        "      phone:        w.phone,\n"
        "      workerCode:   w.workerCode,\n"
        "      isActive:     w.isActive,\n"
        "      assignedCentre: w.assignments?.[0]?.centre || null,\n"
        "    })));\n",

        'expose workerCode in worker list',
    ),
], 'workers.js')


# ════════════════════════════════════════════════════════════════════════
# 4. backend/src/routes/auth.js — Worker ID + Centre ID login
# ════════════════════════════════════════════════════════════════════════
OLD_WORKER_LOGIN = """// ── POST /api/auth/worker/login/ ──────────────────────────────────────────────
const WorkerLoginSchema = z.object({
  centreId: z.string().min(1, 'Centre ID required'),
});

router.post('/worker/login/', async (req, res, next) => {
  try {
    const parsed = WorkerLoginSchema.safeParse(req.body);
    if (!parsed.success)
      return res.status(400).json({ error: 'validation_error', detail: parsed.error.flatten() });

    const { centreId } = parsed.data;

    // Verify centre exists and is active
    const centre = await prisma.centre.findUnique({ where: { centreId } });
    if (!centre || !centre.isActive) {
      await logAction(null, 'WORKER_LOGIN_FAILURE', { req, result: 'centre_not_found', centreId });
      return res.status(401).json({
        error: 'invalid_centre_id',
        detail: 'Centre ID not found. Check with your employer.',
      });
    }

    // Find an active worker assigned to this centre
    // For MVP: if multiple workers share a login, we return the first active one.
    // In production, each worker would have their own pin or NIM + centreId combo.
    const assignment = await prisma.workerCentreAssignment.findFirst({
      where:   { centreId: centre.id, isActive: true },
      include: { worker: true },
      orderBy: { assignedAt: 'asc' },
    });

    // ── No assigned worker: allow anonymous branch access ──────────────────
    // The centre exists and is active but has no workers yet.
    // We issue a short-lived token for the branch itself so the worker
    // dashboard can load (stock, services, notices are branch-scoped, not
    // worker-scoped).  The pseudo-user carries role='worker' so routing works.
    if (!assignment || !assignment.worker.isActive) {
      await logAction(null, 'WORKER_LOGIN_BRANCH_GUEST', { req, result: 'no_workers_branch_guest', centreId });

      // Build a transient guest identity from the centre record
      const owner = await prisma.user.findUnique({
        where: { id: centre.ownerId },
        select: { nim: true, profilePicture: true },
      });

      const guestUser = {
        id:             `guest-${centre.id}`,
        fullName:       centre.name,
        email:          null,
        phone:          null,
        nim:            null,
        profilePicture: owner?.profilePicture ?? null,
        role:           'worker',
        isActive:       true,
        lastLogin:      null,
        centreId:       centre.id,
      };

      const access             = jwtLib.signAccess({ ...guestUser, centreId: centre.id });
      const { token: refresh } = jwtLib.signRefresh({ id: guestUser.id });

      const centreInfo = {
        name:           centre.name,
        location:       centre.location,
        centreId:       centre.centreId,
        brandName:      owner?.nim ?? 'LAIZER STATIONERY',
        profilePicture: owner?.profilePicture ?? null,
      };

      return res.json({
        access,
        refresh,
        user: guestUser,
        centreInfo,
        notice: 'No workers assigned to this centre yet. You have read-only branch access.',
      });
    }
    // ── Regular assigned-worker path ─────────────────────────────────────
    const worker = assignment.worker;
    await prisma.user.update({ where: { id: worker.id }, data: { lastLogin: new Date() } });
    await redis.cacheDel(redis.CacheKey.user(worker.id));

    const access             = jwtLib.signAccess({ ...worker, centreId: centre.id });
    const { token: refresh } = jwtLib.signRefresh(worker);

    await logAction(worker.id, 'WORKER_LOGIN_SUCCESS', { req, result: 'success', centreId });
    const owner = await prisma.user.findUnique({ where: { id: centre.ownerId }, select: { nim:true, profilePicture:true } });
    const centreInfo = { name: centre.name, location: centre.location, centreId: centre.centreId,
      brandName: owner?.nim ?? 'LAIZER STATIONERY', profilePicture: owner?.profilePicture ?? null };
    return res.json({ access, refresh, user: userProfile(worker, centre.id), centreInfo });
  } catch (err) { next(err); }
});"""

NEW_WORKER_LOGIN = """// ── POST /api/auth/worker/login/ ──────────────────────────────────────────────
// """ + MARKER + """
// Centre IDs (STN-XX) are only unique WITHIN one owner's account, so a bare
// Centre ID can no longer safely identify a login on its own once two
// owners share the same string. `workerId` (the workerCode generated at
// registration, e.g. "WK-A1B2") is globally unique and is now the primary
// credential whenever a centre has real workers — Centre ID is only kept
// as a stand-alone login for a brand-new branch that has no workers yet.
const WorkerLoginSchema = z.object({
  workerId: z.string().trim().optional(),
  centreId: z.string().min(1, 'Centre ID required').trim(),
});

router.post('/worker/login/', async (req, res, next) => {
  try {
    const parsed = WorkerLoginSchema.safeParse(req.body);
    if (!parsed.success)
      return res.status(400).json({ error: 'validation_error', detail: parsed.error.flatten() });

    const centreIdInput   = parsed.data.centreId.toUpperCase();
    const workerCodeInput = parsed.data.workerId ? parsed.data.workerId.toUpperCase() : null;

    // ── Path A: Worker ID supplied — authenticate the exact worker ──────────
    // Resolved worker → their own active assignment → that assignment's
    // centre. The Centre ID typed in is only used to CONFIRM the worker is
    // logging into the branch they think they are — it never does the
    // lookup by itself, so two owners' identical Centre IDs can't collide.
    if (workerCodeInput) {
      const worker = await prisma.user.findUnique({ where: { workerCode: workerCodeInput } });
      if (!worker || worker.role !== 'worker' || !worker.isActive) {
        await logAction(null, 'WORKER_LOGIN_FAILURE', { req, result: 'worker_id_not_found', workerCode: workerCodeInput });
        return res.status(401).json({ error: 'invalid_worker_id', detail: 'Worker ID not found. Check with your employer.' });
      }

      const assignment = await prisma.workerCentreAssignment.findFirst({
        where:   { workerId: worker.id, isActive: true },
        include: { centre: true },
        orderBy: { assignedAt: 'desc' },
      });

      if (!assignment || !assignment.centre.isActive) {
        await logAction(worker.id, 'WORKER_LOGIN_FAILURE', { req, result: 'no_active_assignment' });
        return res.status(401).json({ error: 'not_assigned', detail: 'This worker is not currently assigned to any centre.' });
      }

      if (assignment.centre.centreId.toUpperCase() !== centreIdInput) {
        await logAction(worker.id, 'WORKER_LOGIN_FAILURE', { req, result: 'centre_mismatch', centreId: centreIdInput });
        return res.status(401).json({ error: 'centre_mismatch', detail: 'This Worker ID is not registered to that Centre ID.' });
      }

      const centre = assignment.centre;
      await prisma.user.update({ where: { id: worker.id }, data: { lastLogin: new Date() } });
      await redis.cacheDel(redis.CacheKey.user(worker.id));

      const access             = jwtLib.signAccess({ ...worker, centreId: centre.id });
      const { token: refresh } = jwtLib.signRefresh(worker);

      await logAction(worker.id, 'WORKER_LOGIN_SUCCESS', { req, result: 'success', centreId: centre.centreId });
      const owner = await prisma.user.findUnique({ where: { id: centre.ownerId }, select: { nim:true, profilePicture:true } });
      const centreInfo = { name: centre.name, location: centre.location, centreId: centre.centreId,
        brandName: owner?.nim ?? 'LAIZER STATIONERY', profilePicture: owner?.profilePicture ?? null };
      return res.json({ access, refresh, user: userProfile(worker, centre.id), centreInfo });
    }

    // ── Path B: Centre ID only — guest/branch access ─────────────────────────
    // Only allowed when the Centre ID unambiguously identifies a single
    // active centre AND that centre has no worker assigned yet. Any
    // ambiguity (Centre ID shared across owners, or a centre that already
    // has real workers) forces the person to also enter a Worker ID.
    const candidateCentres = await prisma.centre.findMany({ where: { centreId: centreIdInput, isActive: true } });

    if (candidateCentres.length === 0) {
      await logAction(null, 'WORKER_LOGIN_FAILURE', { req, result: 'centre_not_found', centreId: centreIdInput });
      return res.status(401).json({ error: 'invalid_centre_id', detail: 'Centre ID not found. Check with your employer.' });
    }

    if (candidateCentres.length > 1) {
      await logAction(null, 'WORKER_LOGIN_FAILURE', { req, result: 'ambiguous_centre_id', centreId: centreIdInput });
      return res.status(401).json({ error: 'worker_id_required', detail: 'Multiple branches share this Centre ID. Enter your Worker ID to continue.' });
    }

    const centre = candidateCentres[0];
    const assignment = await prisma.workerCentreAssignment.findFirst({
      where:   { centreId: centre.id, isActive: true },
      include: { worker: true },
      orderBy: { assignedAt: 'asc' },
    });

    if (assignment && assignment.worker.isActive) {
      await logAction(null, 'WORKER_LOGIN_FAILURE', { req, result: 'worker_id_required', centreId: centreIdInput });
      return res.status(401).json({ error: 'worker_id_required', detail: 'This centre has registered workers. Enter your Worker ID to continue.' });
    }

    // ── No assigned worker: allow anonymous branch access ──────────────────
    // The centre exists, is active, its Centre ID is unambiguous, and it
    // has no workers yet. We issue a short-lived token for the branch
    // itself so the worker dashboard can load (stock, services, notices
    // are branch-scoped, not worker-scoped).
    await logAction(null, 'WORKER_LOGIN_BRANCH_GUEST', { req, result: 'no_workers_branch_guest', centreId: centreIdInput });

    const owner = await prisma.user.findUnique({
      where: { id: centre.ownerId },
      select: { nim: true, profilePicture: true },
    });

    const guestUser = {
      id:             `guest-${centre.id}`,
      fullName:       centre.name,
      email:          null,
      phone:          null,
      nim:            null,
      profilePicture: owner?.profilePicture ?? null,
      role:           'worker',
      isActive:       true,
      lastLogin:      null,
      centreId:       centre.id,
    };

    const access             = jwtLib.signAccess({ ...guestUser, centreId: centre.id });
    const { token: refresh } = jwtLib.signRefresh({ id: guestUser.id });

    const centreInfo = {
      name:           centre.name,
      location:       centre.location,
      centreId:       centre.centreId,
      brandName:      owner?.nim ?? 'LAIZER STATIONERY',
      profilePicture: owner?.profilePicture ?? null,
    };

    return res.json({
      access,
      refresh,
      user: guestUser,
      centreInfo,
      notice: 'No workers assigned to this centre yet. You have read-only branch access.',
    });
  } catch (err) { next(err); }
});"""

patch_file('backend/src/routes/auth.js', [
    (OLD_WORKER_LOGIN, NEW_WORKER_LOGIN, 'require Worker ID + Centre ID for worker login (owner-safe)'),
], 'auth.js')


# ════════════════════════════════════════════════════════════════════════
# 5. backend/src/lib/redis.js — add reportDetail cache key + TTL
# ════════════════════════════════════════════════════════════════════════
patch_file('backend/src/lib/redis.js', [
    (
        "  reportDaily:   (centreId, date) => `report:d:${centreId}:${date}`,\n"
        "  reportWeekly:  (centreId, ws)   => `report:w:${centreId}:${ws}`,\n"
        "};\n",

        "  reportDaily:   (centreId, date) => `report:d:${centreId}:${date}`,\n"
        "  reportWeekly:  (centreId, ws)   => `report:w:${centreId}:${ws}`,\n"
        "  reportDetail:  (centreId, mode, label) => `report:x:${centreId}:${mode}:${label}`, // " + MARKER + "\n"
        "};\n",

        'add CacheKey.reportDetail',
    ),
    (
        "  REPORT_DAILY:  600,\n"
        "  REPORT_WEEKLY: 1800,\n"
        "};\n",

        "  REPORT_DAILY:  600,\n"
        "  REPORT_WEEKLY: 1800,\n"
        "  REPORT_DETAIL: 300, // " + MARKER + "\n"
        "};\n",

        'add CacheTTL.REPORT_DETAIL',
    ),
], 'redis.js')


# ════════════════════════════════════════════════════════════════════════
# 6. backend/src/routes/services.js — fix report-cache invalidation
# ════════════════════════════════════════════════════════════════════════
patch_file('backend/src/routes/services.js', [
    (
        "const SERVICE_TYPES = ['photocopy', 'printing', 'lamination', 'scanning', 'designing', 'other'];\n"
        "const SUBTYPES      = ['black_and_white', 'colour'];\n",

        "const SERVICE_TYPES = ['photocopy', 'printing', 'lamination', 'scanning', 'designing', 'other'];\n"
        "const SUBTYPES      = ['black_and_white', 'colour'];\n"
        "\n"
        "// " + MARKER + "\n"
        "// Report caches are keyed by EITHER a centreId OR an ownerId (see\n"
        "// reports.js — `centreId || ownerId`, used for the owner's \"all centres\"\n"
        "// dashboard view), plus the per-centre detail-card cache. A wildcard\n"
        "// pattern-delete busts every variant for the affected date/week in one\n"
        "// call, regardless of which id an owner's screen happened to be cached\n"
        "// under — this is what makes new services show up on report cards\n"
        "// immediately instead of only after the cache TTL expires.\n"
        "async function bustReportCaches(centreId, when = new Date()) {\n"
        "  const dateStr   = when.toISOString().slice(0, 10);\n"
        "  const weekStart = new Date(when);\n"
        "  weekStart.setDate(weekStart.getDate() - weekStart.getDay() + 1);\n"
        "  const weekStartStr = weekStart.toISOString().slice(0, 10);\n"
        "\n"
        "  await redis.cacheDelPattern(`report:d:*:${dateStr}`);\n"
        "  await redis.cacheDelPattern(`report:w:*:${weekStartStr}`);\n"
        "  await redis.cacheDelPattern(`report:x:${centreId}:*`);\n"
        "}\n",

        'add bustReportCaches() helper',
    ),
    (
        "    await logAction(req.user.id, logAction.ACTIONS.SERVICE_LOGGED, { req, eventId: event.id });\n"
        "    // Bust report caches for this centre so owner screens reflect the new event immediately.\n"
        "    const todayStr = new Date().toISOString().slice(0, 10);\n"
        "    const weekStart = (() => { const d = new Date(); d.setDate(d.getDate() - d.getDay() + 1); return d.toISOString().slice(0,10); })();\n"
        "    await redis.cacheDel(\n"
        "      redis.CacheKey.reportDaily(req.user.centreId, todayStr),\n"
        "      redis.CacheKey.reportDaily(event.centreId, todayStr),\n"
        "      redis.CacheKey.reportWeekly(req.user.centreId, weekStart),\n"
        "      redis.CacheKey.reportWeekly(event.centreId, weekStart),\n"
        "    );\n"
        "    return res.status(201).json(event);\n",

        "    await logAction(req.user.id, logAction.ACTIONS.SERVICE_LOGGED, { req, eventId: event.id });\n"
        "    await bustReportCaches(event.centreId, new Date(event.createdAt));\n"
        "    return res.status(201).json(event);\n",

        'use bustReportCaches() after logging a service (POST)',
    ),
    (
        "    await logAction(req.user.id, logAction.ACTIONS.SERVICE_EDITED, { req, eventId: req.params.id });\n"
        "    const _todayE = new Date().toISOString().slice(0, 10);\n"
        "    const _wsE = (() => { const d = new Date(); d.setDate(d.getDate() - d.getDay() + 1); return d.toISOString().slice(0,10); })();\n"
        "    await redis.cacheDel(redis.CacheKey.reportDaily(existing.centreId, _todayE), redis.CacheKey.reportWeekly(existing.centreId, _wsE));\n"
        "    return res.json(updated);\n",

        "    await logAction(req.user.id, logAction.ACTIONS.SERVICE_EDITED, { req, eventId: req.params.id });\n"
        "    await bustReportCaches(existing.centreId, new Date(existing.createdAt));\n"
        "    return res.json(updated);\n",

        'use bustReportCaches() after editing a service (PATCH)',
    ),
    (
        "    await logAction(req.user.id, logAction.ACTIONS.SERVICE_DELETED, { req, eventId: req.params.id });\n"
        "    const _todayD = new Date().toISOString().slice(0, 10);\n"
        "    const _wsD = (() => { const d = new Date(); d.setDate(d.getDate() - d.getDay() + 1); return d.toISOString().slice(0,10); })();\n"
        "    await redis.cacheDel(redis.CacheKey.reportDaily(existing.centreId, _todayD), redis.CacheKey.reportWeekly(existing.centreId, _wsD));\n"
        "    return res.json({ detail: 'Service event deleted.' });\n",

        "    await logAction(req.user.id, logAction.ACTIONS.SERVICE_DELETED, { req, eventId: req.params.id });\n"
        "    await bustReportCaches(existing.centreId, new Date(existing.createdAt));\n"
        "    return res.json({ detail: 'Service event deleted.' });\n",

        'use bustReportCaches() after deleting a service (DELETE)',
    ),
], 'services.js')


# ════════════════════════════════════════════════════════════════════════
# 7. backend/src/routes/reports.js — cache the /detail/ card endpoint
# ════════════════════════════════════════════════════════════════════════
patch_file('backend/src/routes/reports.js', [
    (
        "    // Service events in range\n"
        "    let events = [];\n"
        "    try {\n"
        "      events = await prisma.serviceEvent.findMany({\n"
        "        where:  { centreId: centre.id, createdAt: { gte: rangeStart, lt: rangeEnd } },\n"
        "        select: { id:true, serviceType:true, serviceSubtype:true, pages:true,\n"
        "                  pricePerPageTshs:true, totalAmountTshs:true,\n"
        "                  customerNote:true, createdAt:true,\n"
        "                  worker: { select: { fullName:true } } },\n"
        "        orderBy: { createdAt: 'asc' },\n"
        "      });\n",

        "    // " + MARKER + " — serve from cache if a service/stock mutation hasn't\n"
        "    // invalidated it since the last identical request (see services.js\n"
        "    // bustReportCaches()). Speeds up repeated card opens without risking\n"
        "    // staleness, since any mutation busts this exact key immediately.\n"
        "    const cacheKey = redis.CacheKey.reportDetail(centre.id, mode, label);\n"
        "    const cached   = await redis.cacheGet(cacheKey);\n"
        "    if (cached) return res.json(cached);\n"
        "\n"
        "    // Service events in range\n"
        "    let events = [];\n"
        "    try {\n"
        "      events = await prisma.serviceEvent.findMany({\n"
        "        where:  { centreId: centre.id, createdAt: { gte: rangeStart, lt: rangeEnd } },\n"
        "        select: { id:true, serviceType:true, serviceSubtype:true, pages:true,\n"
        "                  pricePerPageTshs:true, totalAmountTshs:true,\n"
        "                  customerNote:true, createdAt:true,\n"
        "                  worker: { select: { fullName:true } } },\n"
        "        orderBy: { createdAt: 'asc' },\n"
        "      });\n",

        'add cache lookup at the top of /reports/detail/',
    ),
    (
        "    return res.json({\n"
        "      centre,\n"
        "      label,\n"
        "      mode,\n"
        "      rangeStart: rangeStart.toISOString(),\n"
        "      rangeEnd:   rangeEnd.toISOString(),\n"
        "      totalEvents:     events.length,\n"
        "      totalRevenueTshs: Math.round(totalRevenue * 100) / 100,\n"
        "      byServiceType:   byType,\n"
        "      events,\n"
        "      stock,\n"
        "    });\n"
        "  } catch (err) { next(err); }\n"
        "});\n"
        "\n"
        "module.exports = router;\n",

        "    const payload = {\n"
        "      centre,\n"
        "      label,\n"
        "      mode,\n"
        "      rangeStart: rangeStart.toISOString(),\n"
        "      rangeEnd:   rangeEnd.toISOString(),\n"
        "      totalEvents:     events.length,\n"
        "      totalRevenueTshs: Math.round(totalRevenue * 100) / 100,\n"
        "      byServiceType:   byType,\n"
        "      events,\n"
        "      stock,\n"
        "    };\n"
        "    await redis.cacheSet(cacheKey, payload, redis.CacheTTL.REPORT_DETAIL);\n"
        "    return res.json(payload);\n"
        "  } catch (err) { next(err); }\n"
        "});\n"
        "\n"
        "module.exports = router;\n",

        'cache the computed payload before returning it',
    ),
], 'reports.js')


# ════════════════════════════════════════════════════════════════════════
# 8. mobile/services/api.ts — authService.workerLogin takes workerId too
# ════════════════════════════════════════════════════════════════════════
patch_file('mobile/services/api.ts', [
    (
        "  workerLogin: (centreId: string) =>\n"
        "    apiClient.post(API_ROUTES.workerLogin, { centreId }),\n",

        "  workerLogin: (workerId: string, centreId: string) => // " + MARKER + "\n"
        "    apiClient.post(API_ROUTES.workerLogin, { workerId: workerId || undefined, centreId }),\n",

        'authService.workerLogin(workerId, centreId)',
    ),
], 'services/api.ts')


# ════════════════════════════════════════════════════════════════════════
# 9. mobile/hooks/useAuth.ts — workerLogin(workerId, centreId)
# ════════════════════════════════════════════════════════════════════════
patch_file('mobile/hooks/useAuth.ts', [
    (
        "  const workerLogin = useCallback(async (centreId: string): Promise<LoginResult> => {\n"
        "    setIsLoading(true); setError(null);\n"
        "    try {\n"
        "      const { data } = await authService.workerLogin(centreId.trim());\n",

        "  const workerLogin = useCallback(async (workerId: string, centreId: string): Promise<LoginResult> => { // " + MARKER + "\n"
        "    setIsLoading(true); setError(null);\n"
        "    try {\n"
        "      const { data } = await authService.workerLogin(workerId.trim(), centreId.trim());\n",

        'useAuth().workerLogin(workerId, centreId)',
    ),
], 'hooks/useAuth.ts')


# ════════════════════════════════════════════════════════════════════════
# 10. mobile/app/(auth)/login.tsx — Worker ID field
# ════════════════════════════════════════════════════════════════════════
patch_file('mobile/app/(auth)/login.tsx', [
    (
        "  const [centreId, setCentreId] = useState('');\n",

        "  const [centreId, setCentreId] = useState('');\n"
        "  const [workerId, setWorkerId] = useState(''); // " + MARKER + "\n",

        'add workerId state',
    ),
    (
        "      if (!centreId.trim()) return;\n"
        "      // workerLogin returns the raw result; the backend may include a `notice`\n"
        "      // field when authorising a branch that has no assigned workers yet.\n"
        "      const result = await workerLogin(centreId.toUpperCase());\n",

        "      if (!centreId.trim()) return;\n"
        "      // workerLogin returns the raw result; the backend may include a `notice`\n"
        "      // field when authorising a branch that has no assigned workers yet.\n"
        "      const result = await workerLogin(workerId.toUpperCase(), centreId.toUpperCase());\n",

        'pass workerId to workerLogin()',
    ),
    (
        '            ) : (\n'
        '              <Input label="Centre ID" placeholder="STN-01"\n'
        '                value={centreId} onChangeText={(t:string) => { setCentreId(t.toUpperCase()); clearError(); }}\n'
        '                autoCapitalize="characters" returnKeyType="done" onSubmitEditing={handleLogin}\n'
        '                hint="Your Centre ID is provided by the shop owner." />\n'
        '            )}\n',

        '            ) : (\n'
        '              <>\n'
        '                <Input label="Worker ID" placeholder="WK-A1B2"\n'
        '                  value={workerId} onChangeText={(t:string) => { setWorkerId(t.toUpperCase()); clearError(); }}\n'
        '                  autoCapitalize="characters" returnKeyType="next"\n'
        '                  hint="Given to you by the shop owner when you were registered. Leave blank only for a brand-new branch with no workers yet." />\n'
        '                <Input label="Centre ID" placeholder="STN-01"\n'
        '                  value={centreId} onChangeText={(t:string) => { setCentreId(t.toUpperCase()); clearError(); }}\n'
        '                  autoCapitalize="characters" returnKeyType="done" onSubmitEditing={handleLogin}\n'
        '                  hint="Your Centre ID is provided by the shop owner." />\n'
        '              </>\n'
        '            )}\n',

        'add Worker ID input above Centre ID input',
    ),
], 'app/(auth)/login.tsx')


# ════════════════════════════════════════════════════════════════════════
# 11. mobile/app/(owner)/workers.tsx — show generated Worker ID
# ════════════════════════════════════════════════════════════════════════
patch_file('mobile/app/(owner)/workers.tsx', [
    (
        "    setSaving(true);\n"
        "    try {\n"
        "      await workerService.register({ fullName: form.fullName.toUpperCase(), phone: form.phone, centreId: form.centreId });\n"
        "      setShowForm(false); setForm(p => ({ fullName:'', phone:'', centreId: p.centreId }));\n"
        "      await load();\n"
        "    } catch (e) { Alert.alert('Error', getApiError(e)); }\n"
        "    finally { setSaving(false); }\n"
        "  };\n",

        "    setSaving(true);\n"
        "    try {\n"
        "      const { data } = await workerService.register({ fullName: form.fullName.toUpperCase(), phone: form.phone, centreId: form.centreId });\n"
        "      setShowForm(false); setForm(p => ({ fullName:'', phone:'', centreId: p.centreId }));\n"
        "      await load();\n"
        "      if (data?.workerCode) { // " + MARKER + "\n"
        "        Alert.alert(\n"
        "          'Worker Registered',\n"
        "          `Give this Worker ID to ${data.fullName ?? 'the worker'} — they need it together with the Centre ID to log in:\\n\\n${data.workerCode}`\n"
        "        );\n"
        "      }\n"
        "    } catch (e) { Alert.alert('Error', getApiError(e)); }\n"
        "    finally { setSaving(false); }\n"
        "  };\n",

        'show generated Worker ID to the owner after registration',
    ),
    (
        "                  <Text style={W.name}>{item.fullName}</Text>\n"
        "                  <Text style={W.sub}>{item.phone}</Text>\n"
        "                  <Text style={W.branch}>{item.assignedCentre ? `\U0001F4CD ${item.assignedCentre.name}` : '\u26A0\uFE0F  Unassigned'}</Text>\n",

        "                  <Text style={W.name}>{item.fullName}</Text>\n"
        "                  <Text style={W.sub}>{item.phone}</Text>\n"
        "                  {item.workerCode ? <Text style={W.sub}>ID: {item.workerCode}</Text> : null}\n"
        "                  <Text style={W.branch}>{item.assignedCentre ? `\U0001F4CD ${item.assignedCentre.name}` : '\u26A0\uFE0F  Unassigned'}</Text>\n",

        'display Worker ID on each worker card',
    ),
], 'app/(owner)/workers.tsx')


# ════════════════════════════════════════════════════════════════════════
# Summary
# ════════════════════════════════════════════════════════════════════════
print()
if CHANGED_FILES:
    ok(f'Patched {len(CHANGED_FILES)} file(s):')
    for f in CHANGED_FILES:
        print(f'   • {f}')
else:
    info('No files needed changes (already patched, or anchors not found — see warnings above).')

if not DRY and CHANGED_FILES:
    print()
    info('NEXT STEPS — the Prisma schema changed, so the DB needs updating:')
    print('   cd backend')
    print('   npx prisma generate')
    print('   npx prisma db push')
    print('   # then restart the backend (Render redeploy / local `npm run dev`)')
    print()
    info("Existing centres keep their current ID until the next delete on that")
    info("owner's account. Existing workers have no Worker ID until re-registered")
    info("(ask if you want a one-off backfill script for that).")
